name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # roda todo dia à meia-noite (UTC)
  workflow_dispatch: {} # permite rodar manualmente pela aba Actions
  push:
    branches:
      - master

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: gcalado55
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=#D0F252&color_dots=#222426,#697345,#92A649,#D0F252,#E3F26D

      - name: Fix dist folder permissions
        run: sudo chown -R $(whoami) dist

      - name: Push snake animation to output branch
        run: |
          cd dist
          git init
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -B output
          git add -A
          git commit -m "Update snake animation"
          git push -f https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git output
